function cfg = config_v4()
%CONFIG_V4  Configuration and hyperparameters - STLF V4 (leak-free pipeline).
%
%   cfg = CONFIG_V4() returns the full configuration struct used by the
%   MATLAB implementation of the STLF V4 forecasting framework.
%
%   Mirrors: SMART_GRIDS_CODE_V4/config.py
%
%   Paper: Adaptive dual-stage signal decomposition and Patch
%          Transformer-BiGRU with cross-attention for short-term load
%          forecasting in smart grids (V4).
%
%   V4 methodological fixes preserved here (tags match the Python code):
%     [FIX-1] Decomposition is CAUSAL and computed inside the model per
%             input window (no CEEMDAN/VMD on the full series).
%     [FIX-2] All scalers are fit on the TRAINING segment only; the model
%             additionally uses RevIN (per-window instance normalization).
%     [FIX-3] Error correction uses only errors observable at issue time.
%     [FIX-4] Outlier treatment is fit on train and NEVER modifies
%             validation/test targets.
%     [FIX-5] Future known covariates (calendar; temperature proxy on
%             GEFCom2014) are provided for the forecast horizon.
%     [FIX-6] Multi-seed protocol + Diebold-Mariano significance testing.
%
%   Requirements: MATLAB R2022b+ and Deep Learning Toolbox only.

% ======================================================================
% PATHS
% ======================================================================
here = fileparts(mfilename('fullpath'));
% Reuse the V3 data directory (datasets already downloaded there).
cfg.data_dir    = fullfile(here, '..', 'SMART_GRIDS_CODE', 'data');
cfg.results_dir = fullfile(here, 'results');
if ~exist(cfg.results_dir, 'dir')
    mkdir(cfg.results_dir);
end

% ======================================================================
% REPRODUCIBILITY  [FIX-6]
% ======================================================================
cfg.seeds        = [42 43 44 45 46];   % multi-seed protocol
cfg.primary_seed = 42;

% ======================================================================
% DATASET CONFIGURATIONS
% ======================================================================
cfg.dataset_names = {'GEFCom2014', 'PJM', 'AEMO'};

cfg.datasets.GEFCom2014 = struct( ...
    'name',            'GEFCom2014', ...
    'csv_file',        'gefcom2014_load.csv', ...
    'resolution',      'hourly', ...
    'steps_per_day',   24, ...
    'input_window',    168, ...      % 1 week
    'pred_horizon',    24, ...       % day-ahead
    'patch_length',    24, ...       % 1 day per patch
    'has_temperature', true, ...
    'train_ratio',     0.70, ...
    'val_ratio',       0.15, ...
    'test_ratio',      0.15);

cfg.datasets.PJM = struct( ...
    'name',            'PJM', ...
    'csv_file',        'PJME_hourly.csv', ...
    'resolution',      'hourly', ...
    'steps_per_day',   24, ...
    'input_window',    168, ...
    'pred_horizon',    24, ...
    'patch_length',    24, ...
    'has_temperature', false, ...
    'train_ratio',     0.70, ...
    'val_ratio',       0.15, ...
    'test_ratio',      0.15);

cfg.datasets.AEMO = struct( ...
    'name',            'AEMO', ...
    'csv_file',        'aemo_nsw.csv', ...
    'resolution',      'half-hourly', ...
    'steps_per_day',   48, ...
    'input_window',    336, ...      % 1 week of half-hours
    'pred_horizon',    48, ...       % day-ahead
    'patch_length',    48, ...
    'has_temperature', false, ...
    'train_ratio',     0.70, ...
    'val_ratio',       0.15, ...
    'test_ratio',      0.15);

% ======================================================================
% CAUSAL ADAPTIVE DUAL-STAGE DECOMPOSITION  [FIX-1]
%   Stage 1: multi-kernel causal moving-average trend/seasonal split.
%   Stage 2: learnable causal band-pass FIR filter bank on the HF
%            residual with an entropy-guided adaptive gate.
% ======================================================================
cfg.decomp = struct( ...
    'stage1_kernels_hours', [12 24 168], ...  % scaled by steps_per_day/24
    'stage2_n_bands',       4, ...
    'stage2_kernel_size',   25, ...           % FIR length (causal, left pad)
    'gate_hidden',          16);

% ======================================================================
% MODEL HYPERPARAMETERS - Proposed CPTB
% (Causal-decomposition Patch Transformer BiGRU with cross-attention)
% ======================================================================
cfg.model = struct( ...
    'd_model',             64, ...
    'n_heads',             4, ...
    'n_encoder_layers',    2, ...
    'dim_feedforward',     128, ...
    'dropout_transformer', 0.1, ...
    'bigru_hidden',        64, ...
    'bigru_layers',        1, ...
    'dropout_bigru',       0.2, ...
    'mlp_hidden',          128, ...
    'dropout_mlp',         0.2, ...
    'cross_att_heads',     2, ...
    'n_future_patches',    4);   % horizon is split into 4 future patches

% ======================================================================
% CAUSAL ERROR CORRECTION  [FIX-3]
%   Trained on VALIDATION errors; at test time it only sees errors of
%   forecasts whose targets are fully realized at issue time.
% ======================================================================
cfg.ec = struct( ...
    'enabled',            true, ...
    'hidden_size',        32, ...
    'input_window_hours', 168, ...   % past observed errors fed to the EC
    'epochs',             50, ...
    'lr',                 1e-3);

% ======================================================================
% TRAINING HYPERPARAMETERS
% ======================================================================
cfg.train = struct( ...
    'epochs',       60, ...
    'batch_size',   64, ...
    'lr',           1e-3, ...
    'weight_decay', 1e-5, ...   % PyTorch-style coupled L2 (added to grads)
    'patience',     10, ...
    'huber_delta',  1.0, ...
    'min_lr',       1e-6, ...
    'grad_clip',    1.0, ...
    'use_gpu',      false);     % set true if Parallel Computing Toolbox +
                                % a supported GPU are available

% ======================================================================
% V4.1 FEATURES
% ======================================================================
% Degree-day covariates (HDD/CDD around the train-median temperature) on
% datasets with temperature; provided to ALL models equally. Mirrors
% USE_DEGREE_DAYS in config.py (round-3 parity).
cfg.use_degree_days = true;

% ======================================================================
% METRICS
% ======================================================================
cfg.metrics = {'MAE', 'RMSE', 'MAPE', 'R2', 'sMAPE'};

end
