#!/usr/bin/env python3
"""Emit every numeric table of the LaTeX manuscript from the released result
files, so that no number in a table is typed by hand.

    python scripts/build_latex_tables.py [--out ../latex/tables]

Inputs (all under results/): Table3/4/5 CSVs (day-ahead results), Table6
ablation CSVs, Table7 efficiency CSV, summary_v4.json (DM tests, ensembles),
rolling_origin_PJM.json, leakage_*.json, covskip_selection.json, mcs_v4.json.
"""
import argparse
import csv
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CODE = os.path.dirname(HERE)
RESULTS = os.path.join(CODE, "results")
DEFAULT_OUT = os.path.join(os.path.dirname(CODE), "latex", "tables")

DS = ["GEFCom2014", "PJM", "AEMO"]
NAME = {"Proposed": "Proposed (CPTB)", "SeasonalNaive": "Seasonal na\\\"ive",
        "CNN_LSTM": "CNN--LSTM", "CNN-LSTM": "CNN--LSTM",
        "GRU_TCN_Attention": "GRU--TCN--Attention",
        "GRU-TCN-Attention": "GRU--TCN--Attention",
        "GRU-TCN-Att.": "GRU--TCN--Att."}
CANON = ["Proposed", "TiDE", "PatchTST", "DLinear", "TCN", "Transformer", "GRU",
         "LSTM", "BiLSTM", "CNN_LSTM", "GRU_TCN_Attention", "XGBoost", "LightGBM",
         "ARIMA", "SeasonalNaive"]


def nm(s):
    return NAME.get(s, s.replace("_", "-"))


def read_csv(path):
    with open(path, encoding="utf-8") as f:
        rows = list(csv.reader(f))
    return rows[0], rows[1:]


def split_pm(cell):
    m = re.match(r"^\s*([-−+]?[\d.,]+)\s*±\s*([\d.,]+)\s*$", cell)
    if not m:
        return cell.strip(), None
    return m.group(1), m.group(2)


def fnum(x):
    return float(str(x).replace("−", "-").replace(",", ""))


def tex_num(x):
    x = str(x).replace("−", "-")
    return "$-$" + x[1:] if x.startswith("-") else x


def tex_pm(mean, std, bold=False):
    s = f"{tex_num(mean)} $\\pm$ {std}" if std is not None else tex_num(mean)
    return f"\\textbf{{{s}}}" if bold else s


def sig(name):
    m = re.match(r"^(.*?)\s*(\*+)$", name)
    return (m.group(1), m.group(2)) if m else (name, "")


def signed(x, nd=2):
    s = f"{x:+.{nd}f}"
    return ("$+$" if s[0] == "+" else "$-$") + s[1:]


def w(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(path))


# ───────────────────────── day-ahead results ─────────────────────────
def results_tables(out):
    files = {"GEFCom2014": "Table3_GEFCom2014.csv", "PJM": "Table4_PJM.csv",
             "AEMO": "Table5_AEMO.csv"}
    units = {"GEFCom2014": "", "PJM": " (MW)", "AEMO": " (MW)"}
    for ds in DS:
        hdr, rows = read_csv(os.path.join(RESULTS, files[ds]))
        parsed = []
        for r in rows:
            name, star = sig(r[0])
            parsed.append((name, star, [split_pm(c) for c in r[1:]]))
        best = []
        for j in range(5):
            vals = [fnum(p[2][j][0]) for p in parsed]
            best.append(max(range(len(vals)), key=lambda i: vals[i]) if j == 3
                        else min(range(len(vals)), key=lambda i: vals[i]))
        # MW-valued MAE/RMSE (PJM, AEMO) are shown to one decimal: the second
        # decimal of a megawatt figure carries no information and widens the table
        def fmt(j, m, s):
            if ds != "GEFCom2014" and j in (0, 1):
                m = f"{fnum(m):.1f}"
                s = None if s is None else f"{fnum(s):.1f}"
            return m, s

        lines = []
        for i, (name, star, cells) in enumerate(parsed):
            label = nm(name) + (f"$^{{{star}}}$" if star else "")
            if name == "Proposed":
                label = f"\\textbf{{{label}}}"
            cs = [tex_pm(*fmt(j, m, s), bold=(best[j] == i)) for j, (m, s) in enumerate(cells)]
            lines.append(" & ".join([label] + cs) + " \\\\")
        body = "\n".join(lines)
        tex = f"""% generated by scripts/build_latex_tables.py from results/{files[ds]}
\\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\\toprule
Model & MAE{units[ds]} & RMSE{units[ds]} & MAPE (\\%) & $R^2$ & sMAPE (\\%) \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
"""
        w(os.path.join(out, f"tab_results_{ds}.tex"), tex)


# ───────────────────────── ablation, both benchmarks in one table ─────────────────────────
ABL_ORDER = [
    ("Full (Proposed)", "Full model"),
    ("w/o Stage 1 (multi-scale split)", "w/o stage 1 (multi-scale causal split)"),
    ("w/o Stage 2 (filter bank)", "w/o stage 2 (learnable filter bank)"),
    ("w/o adaptive gating", "w/o adaptive gate"),
    ("w/o patch embedding", "w/o patch embedding"),
    ("w/o cross-attention", "w/o cross-attention"),
    ("w/o BiGRU decoder", "w/o BiGRU decoder"),
    ("w/o RevIN", "w/o RevIN"),
    ("w/o linear skip", "w/o per-component linear base"),
    ("w/o covariate skip", "w/o full-resolution covariate path"),
    ("w/o future covariates", "w/o future covariates (all pathways)"),
    ("w/ causal error correction", "+ causal error correction"),
]


def ablation_table(out, summary):
    data = {}
    for ds, fn in (("GEFCom2014", "Table6_ablation_GEFCom2014.csv"),
                   ("AEMO", "Table6_ablation_AEMO.csv")):
        hdr, rows = read_csv(os.path.join(RESULTS, fn))
        data[ds] = {r[0]: [split_pm(c) for c in r[1:]] for r in rows}
    # the contrast is computed from the unrounded five-seed means and spreads,
    # so that it agrees with the figures, which read the same file
    raw = summary["ablations"]
    n_seeds = 5
    lines, resolved = [], {}
    for key, label in ABL_ORDER:
        cells = []
        for ds in ("GEFCom2014", "AEMO"):
            full = data[ds]["Full (Proposed)"][2]
            if key not in data[ds]:
                cells += ["n/a", "n/a"]
                continue
            m, s = data[ds][key][2]
            mape = f"{m} $\\pm$ {s}"
            if key == "Full (Proposed)":
                cells += [mape, "---"]
                continue
            rm, rs = raw[ds][key]["mean"]["MAPE"], raw[ds][key]["std"]["MAPE"]
            fm, fstd = raw[ds]["Full (Proposed)"]["mean"]["MAPE"], raw[ds]["Full (Proposed)"]["std"]["MAPE"]
            d = rm - fm
            se = ((rs ** 2 + fstd ** 2) / n_seeds) ** 0.5
            res = abs(d) >= 2 * se
            resolved[(ds, key)] = (d, se, res)
            dtxt = f"{signed(d)} $\\pm$ {se:.2f}"
            cells += [mape, f"\\textbf{{{dtxt}}}" if res else dtxt]
        lines.append(" & ".join([label] + cells) + " \\\\")
    groups = [1, 4, 7, 11]
    body = []
    for i, ln in enumerate(lines):
        if i in groups:
            body.append("\\addlinespace[3pt]")
        body.append(ln)
    tex = f"""% generated by scripts/build_latex_tables.py from results/Table6_ablation_*.csv
\\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\\toprule
 & \\multicolumn{{2}}{{c}}{{GEFCom2014 (covariate-rich)}} & \\multicolumn{{2}}{{c}}{{AEMO (univariate)}} \\\\
\\cmidrule(lr){{2-3}} \\cmidrule(lr){{4-5}}
Variant & MAPE (\\%) & $\\Delta$MAPE (pp) & MAPE (\\%) & $\\Delta$MAPE (pp) \\\\
\\midrule
{chr(10).join(body)}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_ablation.tex"), tex)
    for ds, fn in (("GEFCom2014", "Table6_ablation_GEFCom2014.csv"),
                   ("AEMO", "Table6_ablation_AEMO.csv")):
        hdr, rows = read_csv(os.path.join(RESULTS, fn))
        lab = dict(ABL_ORDER)
        ordered = [r for k, _ in ABL_ORDER for r in rows if r[0] == k]
        ls = [" & ".join([lab[r[0]]] + [tex_pm(*split_pm(c)) for c in r[1:]]) + " \\\\"
              for r in ordered]
        tex = f"""% generated by scripts/build_latex_tables.py from results/{fn}
\\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\\toprule
Variant & MAE & RMSE & MAPE (\\%) & $R^2$ \\\\
\\midrule
{chr(10).join(ls)}
\\bottomrule
\\end{{tabular}}
"""
        w(os.path.join(out, f"tab_ablation_full_{ds}.tex"), tex)
    print("ablation effects (|d| >= 2 SE marked RESOLVED):")
    for (ds, k), (d, se, r) in resolved.items():
        print(f"   {ds:11s} {k:36s} d={d:+.2f} se={se:.3f} t={d/se:+.2f} {'RESOLVED' if r else ''}")


# ───────────────────────── Diebold–Mariano ─────────────────────────
def holm(pvals):
    idx = sorted(range(len(pvals)), key=lambda i: pvals[i])
    m = len(pvals)
    adj = [0.0] * m
    running = 0.0
    for rank, i in enumerate(idx):
        val = min(1.0, (m - rank) * pvals[i])
        running = max(running, val)
        adj[i] = running
    return adj


def fp(p):
    if p < 0.001:
        return "$<$0.001"
    return f"{p:.3f}" if p < 0.01 else f"{p:.2f}"


def dm_table(out, summary):
    base = [m for m in CANON if m != "Proposed"]
    cells, minpos = {}, {}
    for ds in DS:
        dm = summary["results"][ds]["_dm_multiseed"]
        p_mae = holm([dm[b]["p_value_mae"] for b in base])
        for i, b in enumerate(base):
            e = dm[b]
            cells[(ds, b)] = (e["dm_stat"], e["p_holm"], e["dm_mae"], p_mae[i])
        pos = [(round(dm[b]["p_holm"], 3), b) for b in base if dm[b]["dm_stat"] > 0]
        minpos[ds] = min(pos) if pos else None
    order = sorted(base, key=lambda b: cells[("GEFCom2014", b)][0])
    panels = []
    for lname, si in (("Squared-error loss", 0), ("Absolute-error loss", 2)):
        rows = [f"\\multicolumn{{4}}{{@{{}}l}}{{\\emph{{{lname}}}}} \\\\"]
        for b in order:
            row = [nm(b)]
            for ds in DS:
                c = cells[(ds, b)]
                row.append(f"{signed(c[si])} ({fp(c[si + 1])})")
            rows.append(" & ".join(row) + " \\\\")
        panels.append("\n".join(rows))
    tex = f"""% generated by scripts/build_latex_tables.py from results/summary_v4.json (_dm_multiseed)
\\begin{{tabular}}{{@{{}}lccc@{{}}}}
\\toprule
Baseline & GEFCom2014 ($n=259$) & PJM ($n=902$) & AEMO ($n=274$) \\\\
\\midrule
{panels[0]}
\\midrule
{panels[1]}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_dm.tex"), tex)
    print("smallest Holm p among baselines with positive DM (baseline ahead):", minpos)
    for ds in DS:
        dm = summary["results"][ds]["_dm_multiseed"]
        p_mae = holm([dm[b]["p_value_mae"] for b in base])
        neg = [b for b in base if dm[b]["dm_mae"] < 0]
        sig_mae = [(b, round(p_mae[i], 3)) for i, b in enumerate(base)
                   if dm[b]["dm_mae"] < 0 and p_mae[i] < 0.05]
        print(f"  {ds}: negative DM(abs) vs {len(neg)}/14; significant (Holm) under abs loss: {sig_mae}")


# ───────────────────────── ensembles ─────────────────────────
def ensemble_table(out, summary):
    ranks = {}
    for ds, fn in (("GEFCom2014", "Table8b_ensembles_GEFCom2014.csv"),
                   ("PJM", "Table8b_ensembles_PJM.csv"), ("AEMO", "Table8b_ensembles_AEMO.csv")):
        hdr, rows = read_csv(os.path.join(RESULTS, fn))
        dm = summary["results"][ds]["_dm_ensemble"]
        lst = []
        for r in rows:
            model = r[1].replace("-Ens", "")
            key = model.replace("-", "_") + "-Ens"
            star = ""
            if key in dm and dm[key]["dm_stat"] < 0:
                star = "**" if dm[key]["p_holm"] < 0.01 else "*" if dm[key]["p_holm"] < 0.05 else ""
            lst.append((model, r[4], star))
        ranks[ds] = lst
        pos = sorted((round(dm[k]["p_holm"], 3), k) for k in dm if dm[k]["dm_stat"] > 0)
        print(f"ensemble {ds}: baseline ensembles ahead of the proposed ensemble (p_holm, name): {pos}")
    n = max(len(v) for v in ranks.values())
    lines = []
    for i in range(n):
        row = [str(i + 1)]
        for ds in DS:
            model, mape, star = ranks[ds][i]
            lab = nm(model.replace("GRU-TCN-Attention", "GRU_TCN_Attention").replace("CNN-LSTM", "CNN_LSTM"))
            if model == "Proposed":
                lab = "\\textbf{Proposed}"
            row += [lab + (f"$^{{{star}}}$" if star else ""), mape]
        lines.append(" & ".join(row) + " \\\\")
    tex = f"""% generated by scripts/build_latex_tables.py from results/Table8b_ensembles_*.csv and summary_v4.json (_dm_ensemble)
\\begin{{tabular}}{{@{{}}clrlrlr@{{}}}}
\\toprule
 & \\multicolumn{{2}}{{c}}{{GEFCom2014}} & \\multicolumn{{2}}{{c}}{{PJM}} & \\multicolumn{{2}}{{c}}{{AEMO}} \\\\
\\cmidrule(lr){{2-3}} \\cmidrule(lr){{4-5}} \\cmidrule(lr){{6-7}}
Rank & Ensemble & MAPE & Ensemble & MAPE & Ensemble & MAPE \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_ensembles.tex"), tex)


# ───────────────────────── efficiency ─────────────────────────
def efficiency_table(out):
    hdr, rows = read_csv(os.path.join(RESULTS, "Table7_efficiency_GEFCom2014.csv"))
    neural = [r for r in rows if fnum(r[1]) > 0]
    neural.sort(key=lambda r: -fnum(r[1]))
    lines = []
    for r in neural:
        lab = nm(r[0])
        if r[0] == "Proposed":
            lab = f"\\textbf{{{lab}}}"
        lines.append(f"{lab} & {r[1]} & {r[2]} & {r[3]} \\\\")
    lines.append("Non-neural baselines & --- & --- & --- \\\\")
    tex = f"""% generated by scripts/build_latex_tables.py from results/Table7_efficiency_GEFCom2014.csv
\\begin{{tabular}}{{@{{}}lrrr@{{}}}}
\\toprule
Model & Parameters & Train time (s) & Inference (ms) \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_efficiency.tex"), tex)


# ───────────────────────── rolling origin ─────────────────────────
def rolling_table(out):
    with open(os.path.join(RESULTS, "rolling_origin_PJM.json"), encoding="utf-8") as f:
        R = json.load(f)
    models = ["Proposed", "PatchTST", "DLinear"]
    origins = R["origins"]
    heads = [f"{o['val_end']} to {o['test_end']}" for o in origins]
    wins = {m: 0 for m in models}
    for o in origins:
        wins[min(models, key=lambda m: o["models"][m]["mean"]["MAPE"])] += 1
    lines = []
    for m in models:
        cells, vals = [], []
        for o in origins:
            mm = o["models"][m]["mean"]["MAPE"]
            ss = o["models"][m]["std"]["MAPE"]
            vals.append(mm)
            best = min(models, key=lambda k: o["models"][k]["mean"]["MAPE"]) == m
            c = f"{mm:.2f} $\\pm$ {ss:.2f}"
            cells.append(f"\\textbf{{{c}}}" if best else c)
        mean = sum(vals) / len(vals)
        lab = "\\textbf{Proposed (CPTB)}" if m == "Proposed" else nm(m)
        lines.append(" & ".join([lab] + cells + [f"{mean:.2f}", str(wins[m])]) + " \\\\")
    dmtxt = []
    for b in ("PatchTST", "DLinear"):
        st = ", ".join(f"{signed(o['dm'][b]['dm_stat'])} ($p = {o['dm'][b]['p_value']:.2f}$)"
                       for o in origins)
        dmtxt.append(f"against {nm(b)}: {st}")
    tex = f"""% generated by scripts/build_latex_tables.py from results/rolling_origin_PJM.json
\\begin{{tabular}}{{@{{}}lrrrrc@{{}}}}
\\toprule
Model & Period 1 & Period 2 & Period 3 & Mean & Periods won \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_rolling.tex"), tex)
    periods = "; ".join(f"period {i + 1}: {h}" for i, h in enumerate(heads))
    w(os.path.join(out, "rolling_dm_note.tex"),
      "% generated by scripts/build_latex_tables.py\n"
      "\\newcommand{\\rollingDMnote}{Test periods (180 days each): " + periods + ". "
      "Diebold--Mariano statistics of the proposed model per period (squared loss, two-seed mean "
      "prediction, negative favours the proposed model), " + "; ".join(dmtxt) + ".}\n")


# ───────────────────────── leakage ─────────────────────────
def leakage_table(out):
    lines, summary = [], {}
    for ds in ("GEFCom2014", "PJM"):
        with open(os.path.join(RESULTS, f"leakage_{ds}.json"), encoding="utf-8") as f:
            J = json.load(f)
        A2, C = J["protocol_A2_global_ceemdan"], J["protocol_C_causal_ceemdan"]
        A, B = J["protocol_A_decompose_then_split"], J["protocol_B_causal"]
        nd = 2 if ds == "GEFCom2014" else 0

        def row(lab, P):
            cells = [f"{P['MAPE']:.2f}", f"{P['MAE']:.{nd}f}", f"{P['RMSE']:.{nd}f}", f"{P['R2']:.3f}"]
            return " & ".join([lab] + cells) + " \\\\"

        def eff(P1, P2):
            return {k: 100.0 * (P2[k] - P1[k]) / P2[k] for k in ("MAPE", "MAE", "RMSE")}

        em, eu = eff(A2, C), eff(A, B)
        summary[ds] = {"matched": {k: round(v, 1) for k, v in em.items()},
                       "unmatched": {k: round(v, 1) for k, v in eu.items()},
                       "fallback_windows": C.get("_fallback_windows", 0)}
        lines.append(f"\\multicolumn{{5}}{{@{{}}l}}{{\\emph{{{ds}}}}} \\\\")
        lines.append(row("\\quad A2: global CEEMDAN, then split (invalid)", A2))
        lines.append(row("\\quad C: windowed CEEMDAN, causal (valid)", C))
        lines.append(" & ".join(["\\quad Apparent reduction, A2 relative to C (\\%)",
                                 f"\\textbf{{{em['MAPE']:.1f}}}", f"\\textbf{{{em['MAE']:.1f}}}",
                                 f"\\textbf{{{em['RMSE']:.1f}}}", "---"]) + " \\\\")
        lines.append("\\addlinespace[2pt]")
        lines.append(row("\\quad A: global CEEMDAN, one ridge per component", A))
        lines.append(row("\\quad B: causal moving-average split, one ridge", B))
        lines.append(" & ".join(["\\quad Apparent reduction, A relative to B (\\%)",
                                 f"{eu['MAPE']:.1f}", f"{eu['MAE']:.1f}", f"{eu['RMSE']:.1f}", "---"]) + " \\\\")
        if ds == "GEFCom2014":
            lines.append("\\midrule")
    tex = f"""% generated by scripts/build_latex_tables.py from results/leakage_GEFCom2014.json and results/leakage_PJM.json
\\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\\toprule
Protocol & MAPE (\\%) & MAE & RMSE & $R^2$ \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_leakage.tex"), tex)
    print("leakage effects:", json.dumps(summary))


# ───────────────────────── covariate-path selection ─────────────────────────
def covskip_table(out):
    with open(os.path.join(RESULTS, "covskip_selection.json"), encoding="utf-8") as f:
        J = json.load(f)
    lines = []
    for ds in DS:
        e = J["per_dataset"][ds]
        a, b = e["val_MAPE_with_cov_skip"], e["val_MAPE_without_cov_skip"]
        lines.append(f"{ds} & {a['mean']:.3f} $\\pm$ {a['std']:.3f} & {b['mean']:.3f} $\\pm$ {b['std']:.3f} & "
                     f"{signed(e['delta_pp'], 3)} & {'enabled' if e['selected'] else 'disabled'} \\\\")
    tex = f"""% generated by scripts/build_latex_tables.py from results/covskip_selection.json
\\begin{{tabular}}{{@{{}}lrrrl@{{}}}}
\\toprule
Dataset & Validation MAPE with the path (\\%) & without it (\\%) & $\\Delta$ (pp) & Decision \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_covskip.tex"), tex)


# ───────────────────────── model confidence set ─────────────────────────
def mcs_table(out):
    path = os.path.join(RESULTS, "mcs_v4.json")
    if not os.path.exists(path):
        print("mcs_v4.json missing; skipping MCS table")
        return
    with open(path, encoding="utf-8") as f:
        J = json.load(f)
    lines = []
    for m in CANON:
        row = ["\\textbf{Proposed (CPTB)}" if m == "Proposed" else nm(m)]
        for ds in DS:
            for loss in ("mse", "mae"):
                pm = J["datasets"][ds][loss]["p_mcs"]
                if m not in pm:
                    row.append("excl.")
                    continue
                p = pm[m]
                c = f"{p:.2f}" if p >= 0.005 else "$<$0.01"
                row.append(f"\\textbf{{{c}}}" if p >= 0.10 else c)
        lines.append(" & ".join(row) + " \\\\")
    tex = f"""% generated by scripts/build_latex_tables.py from results/mcs_v4.json
\\begin{{tabular}}{{@{{}}lcccccc@{{}}}}
\\toprule
 & \\multicolumn{{2}}{{c}}{{GEFCom2014}} & \\multicolumn{{2}}{{c}}{{PJM}} & \\multicolumn{{2}}{{c}}{{AEMO}} \\\\
\\cmidrule(lr){{2-3}} \\cmidrule(lr){{4-5}} \\cmidrule(lr){{6-7}}
Model & squared & absolute & squared & absolute & squared & absolute \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
"""
    w(os.path.join(out, "tab_mcs.tex"), tex)
    for ds in DS:
        for loss in ("mse", "mae"):
            r = J["datasets"][ds][loss]
            print(f"MCS90 {ds} [{loss}] ({len(r['mcs_90'])} models): {r['mcs_90']}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    with open(os.path.join(RESULTS, "summary_v4.json"), encoding="utf-8") as f:
        summary = json.load(f)
    results_tables(a.out)
    ablation_table(a.out, summary)
    dm_table(a.out, summary)
    ensemble_table(a.out, summary)
    efficiency_table(a.out)
    rolling_table(a.out)
    leakage_table(a.out)
    covskip_table(a.out)
    mcs_table(a.out)


if __name__ == "__main__":
    main()
